### ISSUE TITLE
Anonymous access

### ISSUE THREAD

**Issue by mnexo** [renaudcerrato/appengine-maven-repository#10]
First, thanks for sharing this nice project – really appreciated.

Is there currently a way to allow anonymous read access to the repository?

Thanks!

**Comment by renaudcerrato** [comment]
Mmmm... Anonymous access isn't implemented since I was focusing on private repositories. That could be easily implemented IMO using "*" (or similar) as username? PR are welcome :)

**Comment by Jhonnybmx** [comment]
Thanks for the project, I also need to be able to list anonymously, but I do not know how to do it.

**Comment by renaudcerrato** [comment]
I'm closing since anonymous users have been added in 757ebb8.
