### ISSUE TITLE
Unique release artifact version

### ISSUE THREAD

**Issue by Asdamp** [renaudcerrato/appengine-maven-repository#14]
it would be nice to have an option to refuse artifacts that has the same version of an artifact already uploaded

Example:

1. on the repository i have version 0.6
2. I try to upload a new artifact, with verion 0.6
3. the recpository refuses my upload, forcinjg me to bump version of the artifact

**Comment by renaudcerrato** [comment]
Sounds like a great idea. That could be easily implemented [here](https://github.com/renaudcerrato/appengine-maven-repository/blob/master/src/main/java/repo/resource/RepositoryResource.java#L152). I'm accepting PR btw ;)
