### ISSUE TITLE
Build failed with an exception.

### ISSUE THREAD

**Issue by B0BAI** [renaudcerrato/appengine-maven-repository#16]
Configure project :
WARNING: You are a using release candidate 2.0.0-rc5. Behavior of this plugin has changed since 1.3.5. Please see release notes at: https://github.com/GoogleCloudPlatform/app-gradle-plugin.
Missing a feature? Can't get it to work?, please file a bug at: https://github.com/GoogleCloudPlatform/app-gradle-plugin/issues.
ERROR: (gcloud.app.deploy) The current Google Cloud project [h1r4-maven-repo] does not contain an App Engine application. Use `gcloud app create` to initialize an App Engine application within the project.

> Task :appengineDeploy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':appengineDeploy'.
> com.google.cloud.tools.appengine.AppEngineException: com.google.cloud.tools.appengine.operations.cloudsdk.process.ProcessHandlerException: com.google.cloud.tools.appengine.AppEngineException: Non zero exit: 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 13s
6 actionable tasks: 2 executed, 4 up-to-date

**Comment by renaudcerrato** [comment]
Did you updated your gcloud cli to the latest?

Le lun. 18 févr. 2019 à 20:07, Bobai Kato <notifications@github.com> a
écrit :

**Comment by B0BAI** [comment]
Hi @renaudcerrato I'm I'm using the terminal direct on Google Cloud. Does that count?

**Comment by renaudcerrato** [comment]
Looking at it a second time, it seems you just forgot to create a google app engine project beforehand: `gcloud app create`

**Comment by renaudcerrato** [comment]
Or just use [that link](https://console.cloud.google.com/projectselector/appengine/create?lang=java&st=true)
