### ISSUE TITLE
Error: Not Found on landing page

### ISSUE THREAD

**Issue by matthewcosgrove** [renaudcerrato/appengine-maven-repository#2]
First of all, nice project. It's a great idea for a frictionless way to get a Maven repo up and running. Especially when the best practise approach of using Nexus/Artifactory is cost prohibitive and cumbersome for personal projects.

Following the README page instructions, once the app is deployed, the login is fine via HTTP basic.

Without anything yet deployed to the Maven repo, the first landing page you see after login just says 'Error: Not Found'

I would suggest either

1. This is expected behaviour and should be documented in the README
2. There is an issue which requires a fix

**Comment by renaudcerrato** [comment]
Hi Matthew!

Yes, I'm aware of that, but I didn't took time to fix it. It's happening because your GCS is empty - but I agree that it should not show an error. Will try to find some time to fix, otherwhise, pull requests are welcome =)

**Comment by renaudcerrato** [comment]
Fixed d359b6231605407471d69f2d3c16e9d7d704b41c

**Comment by renaudcerrato** [comment]
FYI @matthewcosgrove, I migrated to mustache as templating engine and I re-wrote the "Index Of" to be apache-like.
