### ISSUE TITLE
Add a gradle module example

### ISSUE THREAD

**Issue by ductranit** [renaudcerrato/appengine-maven-repository#7]
Hi guys,
Thanks for your great library.
I am done deploy my repo as tutorial in ReadMe.
But I don't what's next as well as how to put my module gradle into appegine.
Could you please show a full example which has gradle module code in your project (where to put it and how to config)?
And show how to include this module into main project with private repo
I think it would be make sense for newbie like me, because I just a android developer, and I don't have any experience with Google Cloud
Thank you!

**Comment by renaudcerrato** [comment]
https://docs.gradle.org/current/userguide/dependency_management.html#sec:accessing_password_protected_maven_repositories

```
repositories {
    ...
    maven {
        credentials {
            username 'user'
            password 'password'
        }
        url "https://<yourappid>.appspot.com"
    }
}
```
