### ISSUE TITLE
Remove authorization key in local

### ISSUE THREAD

**Issue by ductranit** [renaudcerrato/appengine-maven-repository#8]
Hi @renaudcerrato , 
Sorry to bother you, but I can't find the way to remove authorization key that generated after run
`/gradlew appengineUpdate`
I want to change the different google account to authorize (also change new app engine app), but it always use the old key for request
I tried to revoke permission from my google account, now I get 401 error when run 
`/gradlew appengineUpdate` again
Do you know where the location of the authorization key? Or do you have any idea? 
Thank!

**Comment by renaudcerrato** [comment]
It is stored in your home directory (Linux), named `.appcfg_oauth2_tokens`
or similar.

**Comment by renaudcerrato** [comment]
http://stackoverflow.com/questions/30227572/how-do-you-reset-app-engines-appcfg-authentication-state
